# Codecov configuration for OPC UA Exporter
# Reference: https://docs.codecov.com/docs/codecov-yaml

# Coverage thresholds
coverage:
  precision: 2  # Number of decimal places (e.g., 85.67%)
  round: down   # How to round coverage percentage
  range: "70...100"  # Color range for coverage badge (red->yellow->green)
  
  status:
    project:
      default:
        target: auto  # Maintain current coverage
        threshold: 1%  # Allow 1% drop before failing
        informational: false  # Fail if threshold not met
    
    patch:
      default:
        target: 80%  # New code should have 80%+ coverage
        threshold: 5%
        informational: false

# Comment on pull requests
comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default  # Update existing comment
  require_changes: false  # Always comment

# Ignore paths
ignore:
  - "tests/"
  - "**/__pycache__/"
  - "**/*.egg-info/"
  - "htmlcov/"
  - "dist/"
  - "build/"
  - "*.pyc"
  - "conftest.py"

# Flags for different test types
flags:
  unittests:
    carryforward: true  # Use previous coverage if flag is missing
    paths:
      - src/opc_browser/

# GitHub checks integration
github_checks:
  annotations: true  # Add annotations to PR

# Codecov.io UI configuration
ui:
  hide_density: false
  hide_complexity: false
